// decleration of variables
const wrapper = document.querySelector(".wrapper");
const search = document.querySelector(".search");
const infoText = document.querySelector(".info-text");
const unList = document.querySelector(".unlist");
const word = document.querySelector(".word");
const details = document.querySelector(".detials");
const content = document.querySelector(".content");
const wordMeaning = document.querySelector(".meaning");
const syn = document.querySelector(".synonmys");
const list = document.querySelector(".list");
const wordExample = document.querySelector(".meaning");
